server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aperissinotto/perissinotto-config-server.git
          search-paths: 'greeting-service*'
          # username: your-username (case of private repositories)
          # password: your-password
          # default-label: main # Specify the default branch if needed (old spring-cloud versions)
  # profiles:
  #   active:
  #     - native # Use 'native' profile to read configuration from local file system