name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # Suporte a ARM64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Habilita build multi-arch
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Java 21
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Build dos microservi√ßos
    - name: Build Exchange Microservice
      working-directory: ./19_MicroservicesRunningInKubernetesCluster/exchange-service
      run: mvn clean package -DskipTests

    - name: Build Book Microservice
      working-directory: ./19_MicroservicesRunningInKubernetesCluster/book-service
      run: mvn clean package -DskipTests

    # Build multi-arch Book Service
    - name: Build & Push Book Service (multi-arch)
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/book-service:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/book-service:kube-v1 \
          -t ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.run_id }} \
          --push \
          ./19_MicroservicesRunningInKubernetesCluster/book-service

    # Build multi-arch Exchange Service
    - name: Build & Push Exchange Service (multi-arch)
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/exchange-service:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/exchange-service:kube-v1 \
          -t ${{ secrets.DOCKER_USERNAME }}/exchange-service:${{ github.run_id }} \
          --push \
          ./19_MicroservicesRunningInKubernetesCluster/exchange-service
